### ISSUE TITLE
Happy New Year

### ISSUE THREAD

**Issue by Yaron10** [Yaron10/compare-plugin#8]
@ClaudiaFrank

Hello Claudia,

I hope you're doing well.
I'd like to wish you a Happy New Year and all the best.

**Comment by ghost** [comment]
Yaron, :-D thank you very much and I wish you and your beloved the same.
Hoping for a peaceful, carefree and successful 2018 for us all.

**Comment by Yaron10** [comment]
👍 
Thank you Claudia.

**Comment by ghost** [comment]
This should have all requested changes
[PythonScript.zip](https://github.com/Yaron10/compare-plugin/files/1948579/PythonScript.zip)

**Comment by Yaron10** [comment]
Hello Claudia,

Thank you very much. I do appreciate it.

The hang issue is indeed solved. :+1: My old DLL had those fixes.
Issue 34 still exists. Have you included your PR? 
And without the code in `startup.py` the console is RTL. I'll look into this myself.

Finding out how to correctly include files and libraries might take me a long time.
If it's not much of a trouble for you, could you please elaborate?
I've downloaded the repo and opened `PythonScript.sln` in the main folder.

Best regards.

**Comment by ghost** [comment]
I guess so

![grafik](https://user-images.githubusercontent.com/16170444/39271564-bda5992e-48d9-11e8-89b6-97b852d11fd4.png)

But I see I missed one, once you created it you cannot edit it using ctrl+click. I will take a look.
Do you see something in addition?

To do the includes/libraries right click on the project page and add to the respective sections

![grafik](https://user-images.githubusercontent.com/16170444/39271724-1be3eefa-48da-11e8-8fb9-f3b7c67eeb75.png)

**Comment by Yaron10** [comment]
> I guess so

Do you mean you've included your PR?

> But I see I missed one, once you created it you cannot edit it using ctrl+click. I will take a look.
Do you see something in addition?

Sorry, I'm not sure I understand that.

> To do the includes/libraries right click on the project page and add to the respective sections

![default](https://user-images.githubusercontent.com/10229320/39274589-2ba6dd6e-48eb-11e8-823f-f2296bd25b09.png)

I see that yours is `PythonScripts Property Pages` and mine is `NppPluginProperty Pages`.
Should I open different solution files?

`Cannot open include file: 'pyconfig.h': No such file or directory`
Where is that file supposed to be?

If you don't have time for this VS mess, just forget it. :)
I'll wait for the official release.  

Thanks again. Highly appreciated.

**Comment by ghost** [comment]
Sorry, yes, I meant I included the PR. As you see from screenshot I was able to create a script
which contains ÄÖÜß and issue 34 was complaining that this isn't possible, so my fix should resolve this
but there is another issue now. If you goto PLugins->PythonScript->Scripts and try to open it by 
pressing CTRL key and clicking the name I do get

![grafik](https://user-images.githubusercontent.com/16170444/39275252-f5c2c3c6-48e4-11e8-984e-16780dc48382.png)

Running it, just clicking on it - works. (Hmmm ???) Seems something is going wrong when providing
the path of the script to notepad++

If you clicked onto the solution file you should see two projects in the solution explorer.
NppPlugin and PythonScript. The changes need to be done in PythonScript property pages.

The pyconfig file is located where you have downloaded your python packages. If you haven't yet, the easiest would be to use the nuget package. In VS2017 goto 
Tools->NugetPackage Manager->Manage Nuget Packages for Solution
Click on Browse tab and type python and rpess enter
you should get one called python2x86 as of version 2.7.14 - click install

But all of this makes only sense if you have two projects listed. If not, try to add the PythonScript project
within the solution explorer.

**Comment by ghost** [comment]
Yaron, do you use IRC? Want to join on  ##npp_ps_dev (on freenode servers) ?

**Comment by Yaron10** [comment]
> but there is another issue now. If you goto PLugins->PythonScript->Scripts and try to open it by
pressing CTRL key and clicking the name I do get

I thought this was 34's OP meaning.
Best of luck with that. I wish I could help. :)
***
Just opened Solution Explorer.
I actually had **4** projects there. I've deleted the test projects.
If you download the repo, don't you get 4?

I'll wait for your clarification on this and try installing the Python package.
***
> Yaron, do you use IRC?

Unfortunately I don't. Thank you.

Thanks again for your time and patience. I do appreciate it.

**Comment by ghost** [comment]
>I thought this was 34's OP meaning.

As OP stated that creation of script wasn't possible ... and this, indeed, wasn't possible my PR should fix it
but you might be correct and the meaning is different - let's see. :-)

You are right - 4 is correct but to be honest, I have deleted, to be correct, removed from solution only,
the other twos because I've added several others to have a better debugging experience. 
I added SciLexer, npp and luascript as well.

**Comment by Yaron10** [comment]
> As OP stated that creation of script wasn't possible ... and this, indeed, wasn't possible my PR should fix it
but you might be correct and the meaning is different - let's see.

Thank you anyway for your PR. :) :+1: 

> You are right - 4 is correct but to be honest, I have deleted the other twos because I've added several
others to have a better debugging experience. I added SciLexer, npp and luascript as well.

Thanks for clarifying. 

I'll try the Python package.

Thank you also for your other PRs and contribution to PythonScript.

Best wishes and good night.

**Comment by ghost** [comment]
Good night

**Comment by Yaron10** [comment]
Hello Claudia,

![default](https://user-images.githubusercontent.com/10229320/39307232-f2749ee8-496a-11e8-95b0-ae2d57fa4d42.png)

Is this also related to your work on 34?
***
I've installed the Python package but `pyconfig.h` is quite stubborn.
I've googled it and came across https://github.com/okfn/piati/issues/65.

I feel I shouldn't take more of your time.
Allow me to thank you again for your kind help and great work.

Best regards.

**Comment by ghost** [comment]
Yes, looks like it does corrupt the menu, but not everywhere ... under investigation.

After installing the python package, did you modify the include and libray directories?
It is not done automatically. If you used NuGet packages you should have a directory called
python2x86.2.7.14 under packages directory.

For me it looks like
D:\Repositories\_cf\Builds\TestNppAndPS\packages\python2x86.2.7.14\tools\
being TestNppAndPS the directory of the solution file.

D:\Repositories\_cf\Builds\TestNppAndPS\packages\python2x86.2.7.14\tools\include\ needs to be added to include section
and 
D:\Repositories\_cf\Builds\TestNppAndPS\packages\python2x86.2.7.14\tools\libs\ to library directory.

**Comment by ghost** [comment]
There is something strange here

Following configuration

![grafik](https://user-images.githubusercontent.com/16170444/39311440-3cc21348-496d-11e8-8c89-7bb3ce65f011.png)

As you see the script ÜberÄÖß.py is saved under Scripts->Überraschung->ÜberÄÖß.py
Using Configuration I added it to the main menu (last entry)

Now the strange things

If I click on the Scripts->Überraschung->ÜberÄÖß.py item, the script runs but corrupts
the Run Previous Script item

![grafik](https://user-images.githubusercontent.com/16170444/39311612-b22cb796-496d-11e8-827e-cd097a6548df.png)

But if I click on the ÜberÄÖß.py in the main menu it doesn't corrupt the Run Previous Script item BUT it does not run.

??? - Seems I need to understand the whole menu creation and execution workflow first in order
to fix this.

**Comment by Yaron10** [comment]
> Yes, looks like it does corrupt the menu, but not everywhere ... under investigation.

This issue existed prior to and regardless of your PR.
I've reported it in issue 20. 

In asking "Is this also related to your work on 34?" I meant: Could you have a look at that too?
Sorry  I wasn't clear enough.

> Now the strange things...

I get the same behavior on my machine.
As for the `Run Previous Script` not being displayed properly whereas the same menu-string is displayed correctly when on its own:
It's either the combination of English with Unicode or the way `Run Previous Script` processes the additional string. 

***

> After installing the python package...

Great. That has finally worked. :)
One last question: now I'm getting `\res\PythonScript.rc(10): fatal error RC1015: cannot open include file 'afxres.h'.`

Thank you very much.

**Comment by ghost** [comment]
When you have open the property page and click edit on the include directory a new window should pop up, within this window you should see an area called **evaluated values**

Content should look like this
D:\Repositories\_cf\Builds\TestNppAndPS\packages\python2x86.2.7.14\tools\Include
D:\Repositories\_cf\Builds\PythonScript\PythonScript\project\..\..\NppPlugin\include
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\atlmfc\include
C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\include

 for library it looks like this

D:\Repositories\_cf\Builds\TestNppAndPS\packages\python2x86.2.7.14\tools\libs
D:\Repositories\_cf\Builds\PythonScript\PythonScript\project\..\..\NppPlugin\bin\release
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\lib
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\atlmfc\lib
C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x86
C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\lib

Could it be that you have installed VS2017 without MFC support?

**Comment by Yaron10** [comment]
> Could it be that you have installed VS2017 without MFC support?

Probably.
I've googled it and replaced `#include "afxres.h"` `with #include <winres.h>`.
The previous error is gone but now I get: `LINK : fatal error LNK1181: cannot open input file 'python27.lib'`.

Thank you.
I thought it was the last question. It's too annoying to quit now.

**Comment by ghost** [comment]
lib = library, what you've done for include you need to do for libraries as well because the includes
define what the libraries do have as code. Both go always hand in hand.

**Comment by Yaron10** [comment]
Thanks again. I appreciate your help.
